# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('removed', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(0, 'On Hold'), (1, 'Registration'), (2, 'Waiting for Event to Start'), (3, 'On Going'), (4, 'Finished')], default=0)),
                ('when_registration_start', models.DateTimeField(blank=True, null=True)),
                ('when_registration_end', models.DateTimeField(blank=True, null=True)),
                ('when_event_start', models.DateTimeField(blank=True, null=True)),
                ('when_event_end', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participated_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='event.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
